### PR TITLE
Revisit the main loop [DO NOT MERGE - not tested :) ]

### PR DESCRIPTION
**Pull request by baylanger**
- Removed `-E` to mosquitto_sub - this prevents the cmd to exit and the loop to relaunch it non stop. Benefits - reduce resource usage (fork, etc).
- added function `ble_listening_loop` that is launched in background. On add-on restart, the docker instance is stopped and relaunch. Includes a var (delay between each presence) that the end-user can configure. Default is `3m` to reflect the previous ~3m.

- side change... send_cmd_retry_delay default value changed from 5 to 5s

NOT Tested yet. Please comment :)

### CODE REVIEW

**Comment by baylanger** [comment]
```
Received MQTT message: tesla_ble/config deploy_key
Configuration deploy_key requested
Deploying public key to vehicle
Attempt 1/5
Error: failed to find BLE beacon for 5YJ3E1EB6JF147926 (Sbd04bf13a78c1f0eC): can't scan: context deadline exceeded
COULD NOT SEND THE KEY. Is the car awake and sufficiently close to the bluetooth device?
Attempt 2/5
2024/06/16 19:57:44 can't accept: skt: can't read hci socket: broken pipe
Error: failed to find BLE beacon for 5YJ3E1EB6JF147926 (Sbd04bf13a78c1f0eC): can't scan: context deadline exceeded
Connecting to MQTT server; subscribe topics tesla_ble/+ and homeassistant/status
Reached 90 MQTT loops (~3min): Launch BLE scanning for car presence
Listening to BLE
```

I believe the err `can't accept: skt: can't read hci socket: broken pipe` is due to a "race condition" between the push key and the ble presence commands. If so and we want this PR, a lock file would fix this race.

**Comment by baylanger** [comment]
I'm now getting this err non-stop.
> Error: failed to find a BLE device: can't init hci: no devices available: (hci0: can't down device: no such device)`

I couldn't find a way in `bluetoothctl` to reset the device.... might need to reboot but not just yet :)  BTW I'm not setup yet... the proximity detection works, the key push doesn't work even when I moved the car closer.

Side note : tesla-control has a "ping" command, not sure if this could be used instead of the proximity detection?  But I'm guessing this is more to know if the car is awake.

**Comment by iainbullock** [comment]
I've done a mod (v1.0.24-dev) in my dev branch to listen for HA restarts as a separate process. Seems to work ok (though I have no car to fully test it)

https://github.com/iainbullock/tesla_ble_mqtt_docker/tree/dev

**Comment by baylanger** [comment]
I had a long procedure at hospital yesterday and had slept ~3hr... I had noticed Sunday `homeassistant/status` but last night when I saw your comment, my brain was in power-off mode :D 

I noticed @raphmur [comment](https://github.com/iainbullock/tesla_ble_mqtt_docker/issues/10#issuecomment-2174336528) in regards to not "spam" BLE discovery.

I didn't know the goal was to move the add-on from this repo to the tesla_ble_mqtt_docker ... my problem is that I'm setup to use the add-on. Going to finish a few of the current PRs and then move to the other repo.

**Comment by BogdanDIA** [comment]
> I'm now getting this err non-stop.
> 
> > Error: failed to find a BLE device: can't init hci: no devices available: (hci0: can't down device: no such device)`
> 
> I couldn't find a way in `bluetoothctl` to reset the device.... might need to reboot but not just yet :) BTW I'm not setup yet... the proximity detection works, the key push doesn't work even when I moved the car closer.
> 
> Side note : tesla-control has a "ping" command, not sure if this could be used instead of the proximity detection? But I'm guessing this is more to know if the car is awake.

You can try this command that works for me most of the times unless there is need for a power restart:
sudo hciconfig hci0 reset

The ping command can be used to detect the car but it does communicate with the car (authenticate and so on). The detection of the car should be passive e.g. the bluetoothctl scan.

**Comment by raphmur** [comment]
> I had a long procedure at hospital yesterday and had slept ~3hr... I had noticed Sunday `homeassistant/status` but last night when I saw your comment, my brain was in power-off mode :D
> 
> I noticed @raphmur [comment](https://github.com/iainbullock/tesla_ble_mqtt_docker/issues/10#issuecomment-2174336528) in regards to not "spam" BLE discovery.
> 
> I didn't know the goal was to move the add-on from this repo to the tesla_ble_mqtt_docker ... my problem is that I'm setup to use the add-on. Going to finish a few of the current PRs and then move to the other repo.

I am not sure we are yet set on the target repo :)
Let's take some chat time when Iain is back from holidays...

**Comment by iainbullock** [comment]
I will be back Sunday afternoon UK time. Back in work on Tuesday. Maybe we have a chat Sunday or Monday sometime - one for the Discord channel

**Pull request closed without merging**
