### PR TITLE
Adjust logging , prevent topic update & ble presence [Splitting in multiple PRs]

### PR DESCRIPTION
**Pull request by baylanger**
[EDIT #2] I am splitting this PR in multiple ones.

[EDIT] ready but read this comment and the 2nd one.

1. PR doesn't fix standalone mode, see PR #17 
2. bashio::log debug should now work properly
3. logic to prevent running BLE presence when BLE_MAC is empty
4. logic to prevent always updating presence topic IF value doesn't change

Will test PR later or most likely Tuesday.

Note for 4. :  not sure if value stays on MQTT restart... maybe we need --retain flag or ?!  Worst case, I can remove the logic.

### CODE REVIEW

**Comment by baylanger** [comment]
PR has been tested w/ a BLE_MAC and w/o one.

For the change 4th change listed above "logic to prevent always updating presence topic IF value doesn't change" , there's actually a bigger issue. If HA is restarted but not this add-on , all values disappear. A restart of the add-on brings everything back.

There is likely a way to detect that HA has restarted and re-run the discovery.sh script as well as publish the presence. That said, I could remove the 4th change but since all values are gone, I hesitate we don't merge the change and figure out after a bit later how to handle a HA restart.

**Comment by iainbullock** [comment]
From https://github.com/iainbullock/tesla_ble_mqtt_docker/issues/10

Regarding detection of HA restarts. I think we need the BLE scanning to be in its own process.

> I originally thought it best to have the BLE scan and the MQTT subsciption in a single thread / process so that there wouldn't be read and write to the bluetooth at the same same. This is the reason I used the -E -c options (so called durable client session) for mosquitto_sub (see https://mosquitto.org/man/mosquitto_sub-1.html ).
> 
> However for this is work the qos for messages send by HA needs to be >=1.
> 
> That's fine for the HA entities as the qos can be specified by auto-discovery. **However it doesn't work for the 'Birth' message sent when HA restarts (which is needed to prevent the entities staying unavailable after a HA restart).** This is because HA sends the Birth message as qos=0 which can't be changed.
> 
> So I'm thinking maybe the BLE scan and MQTT loop should be in separate processes after all. This makes it possible to set the frequency of the BLE scan to be independent of the MQTT loop. There will be times when the processes read and write at the same time, but probably infrequent.

**Comment by baylanger** [comment]
My only concert is the issue I faced yesterday when trying to have both in different processes in #10 

This [comment](https://github.com/raphmur/tesla-local-control-addon/pull/10#issuecomment-2171945333) and the one following.

**Comment by iainbullock** [comment]
Yes I see what you mean. 

Another way maybe to have a mosquitto_sub listening to homeassistant/status in its own process, and when it sees the Birth message call setup_auto_discovery()

This would prevent simultaneous read and write to the bluetooth, but allow regeneration of the HA MQTT auto-discovery when HA restarts

**Comment by baylanger** [comment]
Closing this one.

**Pull request closed without merging**
